version: "0.5"
log_level: debug
log_length: 300

processes:
  clientA:
    working_dir: "clientA"
    is_daemon: true
    command: "sleep 10 && touch ready"
    shutdown:
      command: "rm ready"
    readiness_probe:
      exec:
        command: "echo $(pwd) > ready-check && test -f ready"
  clientB:
    command: "echo all done!"
    depends_on:
      clientA:
        condition: process_healthy

  _pc_log:
    command: "tail -f -n100 process-compose-${USER}.log"
    working_dir: "/tmp"

