version: "0.5"
processes:
  process0:
    command: "ls ddd"

  process1:
    command: "./test_loop.bash ${PROC4}"
    availability:
      restart: "on-failure"
      backoff_seconds: 2
    depends_on:
      process2: 
        condition: process_completed_successfully
      process3: 
        condition: process_completed
      # process4: 
      #   condition: process_completed_successfully
    environment:
      - 'EXIT_CODE=0'

  process2:
    command: "./test_loop.bash process2"
    log_location: ./pc.proc2.log
    availability:
      restart: "on-failure"
    # depends_on:
    #   process3: 
    #     condition: process_completed_successfully
    environment:
      - 'ABC=2221'
      - 'PRINT_ERR=111'
      - 'EXIT_CODE=0'

  process3:
    command: "./test_loop.bash process3"
    availability:
      restart: "on-failure"
      backoff_seconds: 2
    depends_on:
      process4: 
        condition: process_completed_successfully

  process4:
    command: "./test_loop.bash process4"
    # availability:
    #   restart: on-failure
    environment:
      - 'ABC=2221'
      - 'EXIT_CODE=1'

  kcalc:
    command: "kcalc"
    disabled: true

environment:
  - 'ABC=222'
log_location: ./pc.log
