version: "0.5"

log_level: debug
log_length: 1000

processes:
  procA:
    command: "exit 1"
    readiness_probe:
      exec:
        command: "pidof process-compose"
      initial_delay_seconds: 1
      period_seconds: 1
      timeout_seconds: 1
      success_threshold: 1
      failure_threshold: 20

  procB:
    command: echo "I shouldn't run"
    readiness_probe:
      exec:
        command: "pidof process-compose"
      initial_delay_seconds: 1
      period_seconds: 1
      timeout_seconds: 1
      success_threshold: 1
      failure_threshold: 20
    depends_on:
      procA:
        condition: process_healthy

  procC:
    command: echo "I shouldn't run"
    depends_on:
      procB:
        condition: process_healthy

  pc_log:
    command: "tail -f -n100 process-compose-${USER}.log"
    working_dir: "/tmp"
    namespace: debug

