name: docs
on:
  push:
    branches:
      - main
      - docs
    paths:
      - "www/**/*"
      - ".github/workflows/docs.yml"
  pull_request:
    paths:
      - "www/**/*"
      - ".github/workflows/docs.yml"

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: 3.x
      - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg

      - name: Build docs
        if: ${{ github.event_name == 'pull_request' }}
        run: mkdocs build
        working-directory: ./www

      - name: Deploy docs to GitHub Pages
        if: ${{ github.event_name != 'pull_request' }}
        run: mkdocs gh-deploy --force
        working-directory: ./www
