name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Build
      run: go build -v -o process-compose ./src

    - name: Test
      run: go test -v ./src/...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6

